apiVersion: v1
kind: Service
metadata:
  name: sqledge-deployment
  namespace: azure-sql-edge
spec:
  ports:
  - port: 1433
    protocol: TCP
    targetPort: 1433
  selector:
    app: sqledge
  type: LoadBalancer